title: Users
modelClass: Samubra\Exam\Models\User
list: $/samubra/exam/models/user/columns.yaml
recordUrl: 'samubra/exam/users/update/:user_id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
