plugin:
    name: 'samubra.exam::lang.plugin.name'
    description: 'samubra.exam::lang.plugin.description'
    author: samubra
    icon: oc-icon-newspaper-o
    homepage: ''
navigation:
    exam:
        label: 考试管理
        url: samubra/exam/modules
        icon: icon-life-ring
        sideMenu:
            module:
                label: 模块管理
                url: samubra/exam/modules
                icon: icon-sitemap
            subject:
                label: 主题管理
                url: samubra/exam/subjects
                icon: icon-sitemap
            group:
                label: 考试组
                url: samubra/exam/groups
                icon: icon-sitemap
            user:
                label: 考试用户
                url: samubra/exam/users
                icon: icon-sitemap
