title: Subjects
modelClass: Samubra\Exam\Models\Subject
list: $/samubra/exam/models/subject/columns.yaml
recordUrl: 'samubra/exam/subjects/update/:subject_id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
