name: Modules
modelClass: Samubra\Exam\Models\Module
form: $/samubra/exam/models/module/fields.yaml
defaultRedirect: samubra/exam/modules
create:
    redirect: 'samubra/exam/modules/update/:id'
    redirectClose: samubra/exam/modules
update:
    redirect: samubra/exam/modules
    redirectClose: samubra/exam/modules
